[INFLUXDB]
URL = "http://influxdb:8086"
TOKEN = "OyEKjp11bfbhXjghEc2vqeRRZLhkHrl6wMzFWc6lVEKyKSbC6_96TE3ngq2M5IFOBd50mX2N_jVlJXs7JXsPSQ=="
ORG = "RVCE"
BUCKET = "network"

[ADMIN]
USER = "admin"
PASS = "securepassword"